[General]
fontFamily=JetBrainsMono NL Nerd Font
fontSize=11
lastProject=/home/coffin/.local/share/Stickies/new proj 3.vmi

[command_colors]
commandModuleBg=#3b4261
commandModuleTextColor=#4fd6be

[editor_colors]
editorBg=#222436
editorCurrentLineColor=#2f334d
editorCurrentLineNumColor=#e88864
editorFg=#cdd6f4
editorLineNumColor=#6c7086

[mode_colors]
modeModuleInsertBg=#c3e88d
modeModuleNormalBg=#82aaff
modeModuleTextColor=#222436

[note_colors]
noteFiveColor=#c3e88d
noteFourColor=#fcc576
noteOneColor=#65bcff
noteSixColor=#0db9d7
noteTabTextColor=#222436
noteThreeColor=#c099ff
noteTwoColor=#4fd6be
